name: Test CICD
on: 
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  test_cron:
      runs-on: macos-lastest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          if ! command -v brew &> /dev/null; then
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "Homebrew is already installed."
          fi
          
